name: Publish to npm

on: 
  release:
    types:
      - created

jobs: 
  build_pipeline:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      with: 
        node-version: '16'
        registry-url: 'https://registry.npmjs.org'
    - name: Install dependencies
      run: npm install 
    - name: Build with tsc
      run: npm run build
    # - name: Change npm version
    #   run: npm version $new_version
    #   env:
    #     new_version: ${{ github.event.release.tag_name }}
    - name: Publish package on NPM package
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}